### ISSUE TITLE
bin/netgrasp template error

### ISSUE THREAD

**Issue by natej** [jeremyandrews/netgrasp#16]
The install via "(env)$ python setup.py install" went fine. Working from README.md, I tried:
(env)$ netgrasp template
Required [Listen] 'interface' not defined in configuration file, exiting.

Should this work? Maybe I have the CLI syntax wrong?

It looks like it's getting to line 110 in ./bin/netgrasp and calling ng._load_configuration() before the template subparser is used.

Thanks for your time.

**Comment by jeremyandrews** [comment]
Thanks for the bug report -- this is a new regression, will fix.

**Comment by jeremyandrews** [comment]
the intent is to auto-assign and test the Listen interface if not set in the configuration file, but this specific error is fixed with the latest commit -- I'll roll 0.9.3 shortly with this fix.

**Comment by jeremyandrews** [comment]
`pip install netgrasp -U` will install 0.9.3 which fixes this.
https://github.com/jeremyandrews/netgrasp/releases/tag/v0.9.3-beta
